all:
  hosts: {}
  children:
    web_servers:
      hosts:
        web_server_hosts:
          ansible_host: '{{ host_ip }}'
          ansible_user: ubuntu
          ansible_ssh_common_args: -o StrictHostKeyChecking=no
          ansible_ssh_private_key_file: '{{ ssh_key_path }}'
